// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJEKTDB.Data;

#nullable disable

namespace PROJEKTDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117010755_InitGaleria")]
    partial class InitGaleria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROJEKTDB.Models.Fature", b =>
                {
                    b.Property<int>("FatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FatId"));

                    b.Property<DateTime>("FatDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("FAT_DAT");

                    b.Property<string>("PerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PER_ID");

                    b.HasKey("FatId");

                    b.HasIndex("PerId");

                    b.ToTable("FATURE");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Galeri", b =>
                {
                    b.Property<string>("GalId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GAL_ID");

                    b.Property<string>("GalMng")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("GAL_MNG");

                    b.Property<string>("GalTel")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("GAL_TEL");

                    b.Property<string>("GalZon")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("GAL_ZON");

                    b.HasKey("GalId");

                    b.ToTable("GALERI");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Person", b =>
                {
                    b.Property<string>("PerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PER_ID");

                    b.Property<DateTime>("PerDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("PER_DAT");

                    b.Property<string>("PerEm")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PER_EM");

                    b.Property<string>("PerMb")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PER_MB");

                    b.Property<string>("PerTel")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PER_TEL");

                    b.Property<string>("PerZon")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("PER_ZON");

                    b.HasKey("PerId");

                    b.ToTable("PERSON");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Pikture", b =>
                {
                    b.Property<string>("PikId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("PIK_ID");

                    b.Property<string>("GalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GAL_ID");

                    b.Property<string>("PerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PER_ID");

                    b.Property<decimal>("PikCmim")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PIK_CMIM");

                    b.Property<string>("PikTit")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("PIK_TIT");

                    b.HasKey("PikId");

                    b.HasIndex("GalId");

                    b.HasIndex("PerId");

                    b.ToTable("PIKTURE");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Rresht", b =>
                {
                    b.Property<int>("FatId")
                        .HasColumnType("int")
                        .HasColumnName("FAT_ID");

                    b.Property<byte>("RreId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RRE_ID");

                    b.Property<int?>("FatureFatId")
                        .HasColumnType("int");

                    b.Property<string>("PikId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("PIK_ID");

                    b.Property<decimal>("RreCmim")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RRE_CMIM");

                    b.Property<byte>("RreSasi")
                        .HasColumnType("tinyint")
                        .HasColumnName("RRE_SASI");

                    b.HasKey("FatId", "RreId");

                    b.HasIndex("FatureFatId");

                    b.HasIndex("PikId");

                    b.ToTable("RRESHT");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Fature", b =>
                {
                    b.HasOne("PROJEKTDB.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Pikture", b =>
                {
                    b.HasOne("PROJEKTDB.Models.Galeri", "Galeri")
                        .WithMany()
                        .HasForeignKey("GalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJEKTDB.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Galeri");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Rresht", b =>
                {
                    b.HasOne("PROJEKTDB.Models.Fature", "Fature")
                        .WithMany()
                        .HasForeignKey("FatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJEKTDB.Models.Fature", null)
                        .WithMany("Rreshtat")
                        .HasForeignKey("FatureFatId");

                    b.HasOne("PROJEKTDB.Models.Pikture", "Pikture")
                        .WithMany()
                        .HasForeignKey("PikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fature");

                    b.Navigation("Pikture");
                });

            modelBuilder.Entity("PROJEKTDB.Models.Fature", b =>
                {
                    b.Navigation("Rreshtat");
                });
#pragma warning restore 612, 618
        }
    }
}
